export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_DEFULT_USER = 'SET_DEFULT_USER';
export const START_LOADING = 'START_LOADING';
export const FINISH_LOADING = 'FINISH_LOADING';

export const CHANGE_FILED = 'CHANGE_FILED';
export const INITIALIZE_FORM = 'INITIALIZE_FORM'